### ISSUE TITLE
Add: Skip the tracking/analytics URL when opening a link in a tweet

### ISSUE THREAD

**Issue by onewayticket255** [haoict/twitternoads#1]
https://twitter.com/NSExceptional/status/1258132009798549505

```
@interface TFSTwitterEntityURL
@property  NSString* expandedURL;
- (NSString*)url;
@end

%hook TFSTwitterEntityURL
- (NSString*)url{
return self.expandedURL;
}
%end
```

**Comment by haoict** [comment]
Thanks for suggestion, I'll test it and make a new version soon

**Comment by haoict** [comment]
Hi,
Updated to v1.2.0.
Should work fine

**Comment by haoict** [comment]
I also mentioned you in source code
https://github.com/haoict/twitternoads/blob/b140c5e1b683c0abded08b6b02890acc4b742caa/Tweak.xm#L185

**Comment by onewayticket255** [comment]
My pleasure
