### ISSUE TITLE
Ads showing momentarily (until scrolling)

### ISSUE THREAD

**Issue by pkmnct** [haoict/twitternoads#24]
Very recent Twitter update has caused ads to show temporarily (over top of posts).

They disappear if you scroll slightly past them. See screenshots below:

![image](https://user-images.githubusercontent.com/8972556/187283372-3fe7f050-0041-4e25-875a-a973f3d96df4.jpeg)

![image](https://user-images.githubusercontent.com/8972556/187283395-5a581823-48e2-4008-90fd-a57a28a7f5c9.jpeg)

**Comment by SebastianRasch** [comment]
Yep having the same issue!

![image](https://user-images.githubusercontent.com/22617697/188268077-be98b572-1d41-44b3-8d32-1f89c9783835.jpeg)

**Comment by haoict** [comment]
Fixed in version 1.5.0
